# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - base_config
  - _self_
  - data: data.yaml
  - model: unet.yaml
  - callbacks: default.yaml
  - logger: tensorboard
  - trainer: default.yaml
  - mlops: clearml.yaml
  - misc: default.yaml

# seed for random number generators in pytorch, numpy and python.random
seed: 42
