project_name: ml-py-project
task_name: train-minimal-model
task_type: training
base_docker_image: 530073512343.dkr.ecr.eu-central-1.amazonaws.com
execute_on_cluster: true
init_task: true
do_restart_task: false
queue_name: H200-35GiVRAM-60GiRAM-7.5tCPU

tags: [total-segmentator, unet]
