name: ML project branch push workflow

on:
  push:
    branches:
      - '**'

jobs:
  call-workflow:
    uses: snkeos/ana-workflows/.github/workflows/ml-py-project_branch_push.yaml@v5.3.0
    secrets: inherit
    with:
      caller-event: ${{ github.event_name }}
