name: GH -> Azure DO issue sync

on:
  issues:
    types:
      [opened, reopened]

jobs:
  call-workflow:
    uses: snkeos/ana-workflows/.github/workflows/misc_issue_create.yaml@v5.3.0
    secrets: inherit
    with:
      ado_project: "Snke Anatomy"
      ado_work_item_type: "Product Backlog Item"
      parent_work_item: 293865
      ado_area_path: "Snke Anatomy\\MLOps"
