name: ML project pull request workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: snkeos/ana-workflows/.github/workflows/ml-py-project_pull_request.yaml@v5.3.0
    secrets: inherit
    with:
      caller-event: ${{ github.event_name }}
