name: ML project tag push workflow

on:
  push:
    tags:
      - v*

jobs:
  call-workflow:
    uses: snkeos/ana-workflows/.github/workflows/ml-py-project_tag_push.yaml@v5.3.0
    secrets: inherit
    with:
      caller-event: ${{ github.event_name }}
